#193 Theme added(Winter)
DavidMatthewFraser/easy-to-git pull request #207
Opened 2020-10-09 17:44 UTC by anushri20

2020-10-09 19:39 UTC, terrifricker commented on home-page/themes.js
> +  themeName: "winter",
`let winter = {
  themeName: "Winter",`

2020-10-09 19:42 UTC, terrifricker commented on index.html
> +              <a class="dropdown-item" href="#" id="winterTheme">winter Theme</a>
Capitalize Winter in the dropdown menu to keep capitalization consistent with other items in the menu ... `id="winterTheme">Winter Theme</a>`

2020-10-09 19:46 UTC, terrifricker commented
Thank you for the new theme.  The colors are great for a Winter theme.

2020-10-09 20:02 UTC, terrifricker requested changes
You've made good color choices to represent Winter.  I like that they are so cool-colored.  I would like to request one change:

In the index.html file, please capitalize Winter in the drop menu link.  I've marked the spot in the file here in the pull request.

Thank you!

2020-10-10 04:29 UTC, anushri20 commented
Thank you for pointing the changes, I just didn't notice it. I will make the change asap.

2020-10-10 05:13 UTC, terrifricker approved these changes
Wonderful!

2020-10-10 05:14 UTC, merged